import { CloudBridge } from './cloud.js';
const cloud = new CloudBridge();
(()=>{
const isAndroid=/Android/i.test(navigator.userAgent);
document.documentElement.classList.toggle('android',isAndroid);
const syncVH=()=>document.documentElement.style.setProperty('--app-vh',`${window.innerHeight}px`);
syncVH(); window.addEventListener('resize',syncVH,{passive:true});
const BASE_LS_KEY='meal_stamp_app_v4'; let cloudReady=false, syncTimer=null, remoteReloadTimer=null;
function cacheKey(){return cloud.space?cloud.cacheKey():BASE_LS_KEY+'_precloud'}
function isAdmin(){return cloud.role==='admin'}
const DEFAULT={settings:{targetDays:22,rewardEvery:15,demo:false,passwordHash:'',startDate:''},checkins:{},rewards:[{id:uid(),name:'奶茶一杯',enabled:true},{id:uid(),name:'按摩 20 分钟',enabled:true},{id:uid(),name:'指定一顿想吃的',enabled:true},{id:uid(),name:'免做一次家务',enabled:true}],rewardHistory:[],makeups:[],chores:[{id:uid(),name:'洗碗 + 收厨房',credit:1},{id:uid(),name:'扫地拖地',credit:1},{id:uid(),name:'整理衣物',credit:1},{id:uid(),name:'深度收纳一块区域',credit:2}],choreRequests:[]};
let state=clone(DEFAULT); let galleryUrls=[]; let calCursor=new Date(); calCursor.setDate(1); let wheelDeg=0; let db;
function uid(){return Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-4)}
function clone(o){return JSON.parse(JSON.stringify(o))}
function load(){try{let x=JSON.parse(localStorage.getItem(cacheKey()));if(x)return Object.assign(clone(DEFAULT),x,{settings:Object.assign({},DEFAULT.settings,x.settings||{})})}catch(e){} return clone(DEFAULT)}
function scheduleCloudSync(){if(!cloudReady)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncNow(),450)}
async function syncPendingPhotos(){for(const [day,v] of Object.entries(state.checkins||{})){for(const meal of ['lunch','dinner']){let x=v?.[meal];if(x?.status&&x.photoId&&!x.photoPath){let blob=await getPhoto(x.photoId);if(blob){x.photoPath=await cloud.uploadPhoto(day,meal,x.photoId,blob)}}}}}
async function syncNow(){if(!cloudReady||!navigator.onLine)return;try{setSyncStatus('同步中…');await syncPendingPhotos();await cloud.syncState(state);localStorage.setItem(cacheKey(),JSON.stringify(state));setSyncStatus('已同步 ☁️')}catch(e){console.error(e);setSyncStatus('离线缓存中')}}
function save(){localStorage.setItem(cacheKey(),JSON.stringify(state));renderAll();scheduleCloudSync();if(cloudReady)setTimeout(ensureStartDate,0)}
function ymd(d=new Date()){let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function ym(d=new Date()){return ymd(d).slice(0,7)}
function fmtDate(s){let [y,m,d]=s.split('-');return `${y}.${m}.${d}`}
function monthLabel(s){let [y,m]=s.split('-');return `${y} 年 ${+m} 月`}
function parseYmdLocal(s){let [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)}
function addDaysLocal(s,n=1){let d=parseYmdLocal(s);d.setDate(d.getDate()+n);return ymd(d)}
function getDay(s){return state.checkins[s]||{}}
function mealDone(v){return !!(v&&v.status)}
function fullDay(s){let d=getDay(s);return mealDone(d.lunch)&&mealDone(d.dinner)}
function getMonthDays(mon){return Object.keys(state.checkins).filter(k=>k.startsWith(mon)&&fullDay(k)).length}
function approvedChoreCredit(mon){return state.choreRequests.filter(x=>x.month===mon&&x.status==='approved').reduce((a,b)=>a+(+b.credit||0),0)}
function effectiveMonthDays(mon){return getMonthDays(mon)+approvedChoreCredit(mon)}
function monthState(mon){let now=ym();let n=effectiveMonthDays(mon),target=+state.settings.targetDays;if(mon>now)return {status:'future',n}; if(mon===now)return {status:n>=target?'valid':'ongoing',n}; return {status:n>=target?'valid':'invalid',n}}
function eligibleStampDays(){let months=new Set(Object.keys(state.checkins).map(k=>k.slice(0,7)));state.choreRequests.forEach(x=>months.add(x.month));let cur=ym();months.add(cur);let sum=0; months.forEach(m=>{let ms=monthState(m); if(m===cur)sum+=getMonthDays(m); else if(ms.status==='valid')sum+=effectiveMonthDays(m)}); return sum}
function claimed(){return state.rewardHistory.filter(x=>!x.test).length}
function realRewardTurns(){return Math.max(0,Math.floor(eligibleStampDays()/(+state.settings.rewardEvery||15))-claimed())}
function rewardTurns(){return state.settings.demo?Infinity:realRewardTurns()}
function canPlayReward(){return state.settings.demo||realRewardTurns()>0}
function streak(){let d=new Date(),n=0;while(true){let s=ymd(d);if(fullDay(s)){n++;d.setDate(d.getDate()-1)}else{if(s===ymd()) {d.setDate(d.getDate()-1);continue;} break}}return n}
function statusLabel(v){return v?.status==='makeup'?'补签':'准时'}
function mealWindow(meal,now=new Date()){if(state.settings.demo)return {open:true,label:'体验模式'};let min=now.getHours()*60+now.getMinutes();let [a,b]=meal==='lunch'?[720,840]:[1020,1439];return {open:min>=a&&min<=b,before:min<a,after:min>b,label:min<a?'未开始':min>b?'已结束':'可打卡'}}
function toast(msg){let el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function $(s,r=document){return r.querySelector(s)} function $$(s,r=document){return [...r.querySelectorAll(s)]}

async function initDB(){db=await new Promise((res,rej)=>{let r=indexedDB.open('meal_stamp_photos',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});renderAll()}
function putPhoto(id,blob){return new Promise((res,rej)=>{let tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(blob,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function getPhoto(id){return new Promise((res,rej)=>{if(!db)return res(null);let r=db.transaction('photos').objectStore('photos').get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
function delPhoto(id){return new Promise((res)=>{if(!db||!id)return res();let tx=db.transaction('photos','readwrite');tx.objectStore('photos').delete(id);tx.oncomplete=res;tx.onerror=res})}
async function compress(file){
  const TARGET=240*1024, MAX=300*1024, MIN_Q=.48, MAX_Q=.84;
  let bmp=await createImageBitmap(file), maxSide=1280;
  let scale=Math.min(1,maxSide/Math.max(bmp.width,bmp.height));
  let w=Math.max(1,Math.round(bmp.width*scale)), h=Math.max(1,Math.round(bmp.height*scale));
  const encode=(cw,ch,q)=>new Promise((resolve,reject)=>{const c=document.createElement('canvas');c.width=cw;c.height=ch;const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,cw,ch);ctx.drawImage(bmp,0,0,cw,ch);c.toBlob(b=>b?resolve(b):reject(new Error('图片压缩失败')),'image/jpeg',q)});
  let blob=null;
  for(let round=0;round<3;round++){
    let lo=MIN_Q,hi=MAX_Q,best=null;
    for(let i=0;i<6;i++){
      const q=(lo+hi)/2,b=await encode(w,h,q);
      if(!best||Math.abs(b.size-TARGET)<Math.abs(best.size-TARGET))best=b;
      if(b.size>TARGET)hi=q;else lo=q;
    }
    blob=best;
    if(blob.size<=MAX)break;
    const shrink=Math.max(.72,Math.sqrt(MAX/blob.size)*.94);
    w=Math.max(720,Math.round(w*shrink));h=Math.max(720,Math.round(h*shrink));
  }
  bmp.close();
  return blob;
}
async function handleUpload(meal,file){let win=mealWindow(meal);if(!win.open){toast(meal==='lunch'?'午餐只能在 12:00–14:00 打卡':'晚餐只能在 17:00–23:59 打卡');return}if(!file||!file.type.startsWith('image/')){toast('请选择图片文件');return}toast('正在压缩照片…');try{let blob=await compress(file);let id=uid();await putPhoto(id,blob);let day=ymd(),cur=getDay(day)[meal];if(cur?.photoId)await delPhoto(cur.photoId);state.checkins[day]=state.checkins[day]||{};let photoPath=null;if(cloudReady&&navigator.onLine){try{photoPath=await cloud.uploadPhoto(day,meal,id,blob)}catch(e){console.warn('photo upload queued',e)}}state.checkins[day][meal]={status:'onTime',time:new Date().toISOString(),photoId:id,photoPath,bytes:blob.size};save();toast(`打卡成功 · 已压缩到 ${Math.round(blob.size/1024)} KB${photoPath?' · 已上传云端':' · 等待同步'}`)}catch(e){console.error(e);toast('图片处理失败，请换一张试试')}}
async function renderMeal(meal){let day=getDay(ymd()),v=day[meal],up=$('#upload-'+meal),st=$('#'+meal+'Status'),win=mealWindow(meal);if(v&&v.status){st.className='status ok';st.textContent=v.status==='makeup'?'已补签':'已完成';if(v.photoId){let blob=await getPhoto(v.photoId);if(!blob&&v.photoPath&&cloudReady&&navigator.onLine){try{blob=await cloud.downloadPhoto(v.photoPath);await putPhoto(v.photoId,blob)}catch(e){console.warn(e)}}if(blob){let url=URL.createObjectURL(blob);up.innerHTML=`<img class="photo" src="${url}"><div class="photo-over"><span>${v.status==='makeup'?'补签':'准时打卡'} · ${Math.round((v.bytes||blob.size)/1024)} KB</span><button class="btn soft" data-remove-photo="${meal}" style="padding:6px 9px">重拍</button></div>`;return}}up.innerHTML=`<div class="empty"><div class="big">✅</div><b>${v.status==='makeup'?'补签已通过':'这餐已打卡'}</b><span>${v.status==='makeup'?'没有照片也会计入餐次':'照片已保存到本机'}</span></div>`} else {st.className='status '+(win.open?'open':win.after?'late':'');st.textContent=win.label;up.innerHTML=`<input type="file" accept="image/*" id="file-${meal}" aria-label="选择${meal==='lunch'?'午餐':'晚餐'}照片"><div class="empty"><div class="big">${meal==='lunch'?'📷':'📸'}</div><b>上传一张${meal==='lunch'?'午餐':'晚餐'}照片</b><span>点击或拖入图片 · 自动压缩</span><div style="margin-top:10px"><button class="btn ${meal==='lunch'?'yellow-btn':'primary'}" data-upload="${meal}" ${win.open?'':'disabled'}>选择照片</button></div></div>`;attachUpload(meal)}}
function attachUpload(meal){let up=$('#upload-'+meal),fi=$('#file-'+meal);if(!up||!fi)return;up.onclick=e=>{if(e.target.closest('button[data-upload]'))fi.click()};fi.onchange=()=>handleUpload(meal,fi.files[0]);['dragenter','dragover'].forEach(x=>up.addEventListener(x,e=>{e.preventDefault();up.classList.add('drag')}));['dragleave','drop'].forEach(x=>up.addEventListener(x,e=>{e.preventDefault();up.classList.remove('drag')}));up.addEventListener('drop',e=>handleUpload(meal,e.dataTransfer.files[0]))}

function renderToday(){let now=new Date(),day=getDay(ymd()),done=[mealDone(day.lunch),mealDone(day.dinner)].filter(Boolean).length;$('#clockPill').textContent=now.toLocaleString('zh-CN',{month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'});$('#todayText').textContent=`${monthLabel(ym(now))} · 完成两次上传即可盖章`;$('#dayStatusPill').textContent=`今日 ${done} / 2`;$('#statMonthDays').textContent=getMonthDays(ym());$('#statRewardTurns').textContent=state.settings.demo?'∞':realRewardTurns();$('#statStreak').textContent=streak();$('#statPending').textContent=state.makeups.filter(x=>x.status==='pending').length+state.choreRequests.filter(x=>x.status==='pending').length;let full=done===2;$('#todayStamp').textContent=full?'🌼':'🌱';$('#todayStampTitle').textContent=full?'今天的完整印章已盖好！':'今天的印章还在等你';$('#todayStampDesc').textContent=full?'午餐和晚餐都完成啦，今天计入 1 个完整集章日。':'完成午餐和晚餐打卡后，就会变成完整印章 🌼';renderMeal('lunch');renderMeal('dinner')}
function renderCalendar(){renderPhotoGallery();let mon=ym(calCursor),year=calCursor.getFullYear(),month=calCursor.getMonth(),first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),start=(first.getDay()+6)%7;$('#monthTitle').textContent=monthLabel(mon);$('#calMonthStat').textContent=`${month+1} 月`;let ms=monthState(mon),target=+state.settings.targetDays,n=getMonthDays(mon),credit=approvedChoreCredit(mon),eff=n+credit;$('#calDaysStat').textContent=`${eff} / ${target}`;$('#calProgress').style.width=Math.min(100,eff/target*100)+'%';$('#calGapText').textContent=eff>=target?'已达到月目标 🎉':`还差 ${target-eff} 天`;$('#calChoreStat').textContent=credit;let statusMap={valid:'本月有效',invalid:'本月失效',ongoing:'本月进行中',future:'未来月份'};$('#calMonthStatus').textContent=statusMap[ms.status];let html=['一','二','三','四','五','六','日'].map(x=>`<div class="dow">周${x}</div>`).join('');for(let i=0;i<start;i++)html+='<div class="day blank"></div>';for(let d=1;d<=days;d++){let s=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,v=getDay(s),l=v.lunch,r=v.dinner,full=fullDay(s);let lc=l?.status==='makeup'?'makeup':l?.status?'ok':'',rc=r?.status==='makeup'?'makeup':r?.status?'ok':'';html+=`<div class="day ${s===ymd()?'today':''}"><span class="n">${d}</span><div class="dots"><i class="dot ${lc}"></i><i class="dot ${rc}"></i></div>${full?'<span class="stamp">🌼</span>':''}<span class="mini">${full?'完整':'午 / 晚'}</span></div>`}$('#calendarGrid').innerHTML=html;renderMonthHistory()}

async function renderPhotoGallery(){
  const box=$('#photoGallery'); if(!box)return; galleryUrls.forEach(u=>URL.revokeObjectURL(u)); galleryUrls=[];
  const items=[]; for(const day of Object.keys(state.checkins||{}).sort().reverse()){for(const meal of ['dinner','lunch']){const x=state.checkins[day]?.[meal];if(x?.photoId)items.push({day,meal,x});if(items.length>=12)break}if(items.length>=12)break}
  if(!items.length){box.innerHTML='<div class="empty-state" style="grid-column:1/-1">还没有上传过照片 📷</div>';return}
  box.innerHTML=items.map((it,i)=>`<div class="gallery-item" id="gallery-${i}"><div style="aspect-ratio:4/3;display:grid;place-items:center;color:var(--muted);font-size:12px">正在读取照片…</div><div class="gallery-meta"><b>${fmtDate(it.day)} · ${it.meal==='lunch'?'午餐':'晚餐'}</b>${it.x.status==='makeup'?'补签':'准时打卡'}</div></div>`).join('');
  for(let i=0;i<items.length;i++){let {x}=items[i],blob=await getPhoto(x.photoId);if(!blob&&x.photoPath&&cloudReady&&navigator.onLine){try{blob=await cloud.downloadPhoto(x.photoPath);await putPhoto(x.photoId,blob)}catch(e){console.warn(e)}}let host=$(`#gallery-${i}`);if(blob&&host){let u=URL.createObjectURL(blob);galleryUrls.push(u);host.firstElementChild.outerHTML=`<img src="${u}" alt="${items[i].day} ${items[i].meal==='lunch'?'午餐':'晚餐'}打卡照片">`}else if(host){host.firstElementChild.textContent='照片暂未同步到本机'}}
}

function renderMonthHistory(){let months=new Set([ym()]);Object.keys(state.checkins).forEach(k=>months.add(k.slice(0,7)));state.choreRequests.forEach(x=>months.add(x.month));let arr=[...months].sort().reverse().slice(0,12);$('#monthHistory').innerHTML=arr.map(m=>{let raw=getMonthDays(m),credit=approvedChoreCredit(m),eff=raw+credit,ms=monthState(m),cl=ms.status==='valid'?'valid':ms.status==='invalid'?'invalid':'ongoing',tx=ms.status==='valid'?(credit?'补救有效':'有效'):ms.status==='invalid'?'失效':'进行中';return `<div class="month-row"><b>${monthLabel(m).replace(' 年 ','/').replace(' 月','')}</b><div><div class="bar"><i style="width:${Math.min(100,eff/state.settings.targetDays*100)}%"></i></div><small style="color:var(--muted)">${raw} 打卡${credit?` + ${credit} 家务`:''} / ${state.settings.targetDays}</small></div><span class="${cl}">${tx}</span></div>`}).join('')}
function renderWheel(){let active=state.rewards.filter(x=>x.enabled),wheel=$('#wheel');if(!wheel)return;if(!active.length){wheel.style.background='#F3E8EC';wheel.innerHTML='';return}let colors=['#FFD85A','#FFB4CB','#BEE7D8','#C8BDF6','#FFE7A0','#FFCDD9','#CDEEDC','#D9D2FF','#FFD4A8','#F6C5E4','#BFE5F2','#D8E8AE'];let step=360/active.length,parts=active.map((r,i)=>`${colors[i%colors.length]} ${i*step}deg ${(i+1)*step}deg`);wheel.style.background=`conic-gradient(${parts.join(',')})`;let radius=active.length<=4?84:active.length<=8?91:active.length<=12?96:100;let cls=active.length>12?' very-dense':active.length>8?' dense':'';wheel.innerHTML=active.map((r,i)=>{let a=(i+.5)*step;return `<span class="wheel-label${cls}" style="transform:translate(-50%,-50%) rotate(${a}deg) translateY(-${radius}px) rotate(${-a}deg)">${esc(r.name)}</span>`}).join('')}
function renderRewards(){let active=state.rewards.filter(x=>x.enabled),test=!!state.settings.demo;$('#rewardStampCount').textContent=eligibleStampDays();$('#claimedCount').textContent=claimed();$('#rewardTurns').textContent=test?'∞':realRewardTurns();$('#rewardPlayHint').textContent=test?'🧪 测试模式：抽奖和翻牌不限次数，测试结果不消耗正式奖励':'每次开奖消耗 1 次可用奖励';$('#rewardList').innerHTML=state.rewards.length?state.rewards.map(r=>`<div class="reward-row"><div><div class="reward-name">${esc(r.name)}</div><div class="reward-meta">${r.enabled?'已加入等概率奖池':'已停用'}</div></div>${isAdmin()?`<div class="inline"><button class="btn soft" data-toggle-reward="${r.id}" style="padding:7px 9px">${r.enabled?'停用':'启用'}</button><button class="btn danger" data-del-reward="${r.id}" style="padding:7px 9px">删除</button></div>`:''}</div>`).join(''):'<div class="empty-state">还没有奖励，先添加几个吧 🎁</div>';renderWheel();$('#spinBtn').disabled=!canPlayReward()||active.length<1;renderFlipCards();$('#rewardHistory').innerHTML=state.rewardHistory.length?state.rewardHistory.slice().reverse().map(x=>`<div class="request-item"><div><b>🎁 ${esc(x.reward)}</b><p>${new Date(x.time).toLocaleString('zh-CN')} · ${x.mode==='wheel'?'抽奖转盘':'翻牌'}${x.test?' · 测试记录':''}</p>${x.completedAt?`<div class="reward-complete-time" style="text-align:left;margin-top:5px">完成时间：${new Date(x.completedAt).toLocaleString('zh-CN')}</div>`:''}</div><div class="reward-history-actions"><span class="tag ${x.completed?'approved':x.test?'pending':'approved'}">${x.completed?'已完成':x.test?'测试':'已领取'}</span>${x.completed?'':`<button class="btn mint-btn" data-complete-reward="${x.id}" style="padding:7px 11px">完成</button>`}</div></div>`).join(''):'<div class="empty-state">还没有开奖记录，继续攒印章吧 ✨</div>'}
function renderFlipCards(){let active=shuffle(state.rewards.filter(x=>x.enabled));let box=$('#flipCards');if(!box)return;box.innerHTML=active.length?active.map(r=>`<div class="flip ${!canPlayReward()?'disabled':''}" data-flip="${r.id}"><div class="inner"><div class="face front">💌</div><div class="face back">${esc(r.name)}</div></div></div>`).join(''):'<div class="empty-state" style="grid-column:1/-1">请先添加并启用奖励</div>'}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function claimReward(reward,mode){if(!canPlayReward()){toast('还没有可用开奖次数');return}let test=!!state.settings.demo;state.rewardHistory.push({id:uid(),reward,time:new Date().toISOString(),mode,test,completed:false,completedAt:null});save();showResult(reward,test)}
function completeReward(id){let item=state.rewardHistory.find(x=>x.id===id);if(!item||item.completed)return;item.completed=true;item.completedAt=new Date().toISOString();save();toast('奖励已标记完成 ✓')}
function showResult(reward,test=false){modal(`<h3>${test?'🧪 测试抽中！':'🎉 抽中啦！'}</h3><p>${test?'本次是测试结果，不会消耗正式奖励次数。':'这次的奖励是：'}</p><div class="result">${esc(reward)}</div><div class="modal-actions"><button class="btn primary" data-close-modal>${test?'继续测试':'开心收下'}</button></div>`)}
function spin(){let active=state.rewards.filter(x=>x.enabled);if(!active.length||!canPlayReward())return;let idx=Math.floor(Math.random()*active.length),step=360/active.length,target=360-(idx+.5)*step,current=((wheelDeg%360)+360)%360,targetNorm=((target%360)+360)%360,delta=(targetNorm-current+360)%360;wheelDeg+=1440+delta;$('#wheel').style.transform=`rotate(${wheelDeg}deg)`;$('#spinBtn').disabled=true;setTimeout(()=>claimReward(active[idx].name,'wheel'),3350)}

function missedSlots(now=new Date()){if(!state.settings.startDate)return [];let start=state.settings.startDate,today=ymd(now);if(start>today)return [];let min=now.getHours()*60+now.getMinutes(),out=[];for(let s=start;s<=today;s=addDaysLocal(s,1)){for(let meal of ['lunch','dinner']){if(mealDone(getDay(s)[meal]))continue;let expired=s<today||(s===today&&min>(meal==='lunch'?840:1439));if(!expired)continue;let pending=state.makeups.find(x=>x.date===s&&x.meal===meal&&x.status==='pending');let rejected=state.makeups.some(x=>x.date===s&&x.meal===meal&&x.status==='rejected');out.push({date:s,meal,pending:!!pending,rejected})}}return out.reverse()}
function renderMakeups(){let pending=state.makeups.filter(x=>x.status==='pending').length,slots=missedSlots();$('#pendingMakeupCount').textContent=`${pending} 个待审核补签`;$('#makeupStartDate').textContent=state.settings.startDate?`起始 ${fmtDate(state.settings.startDate)}`:'尚未绑定';$('#missingMakeupList').innerHTML=slots.length?slots.map(x=>`<div class="missing-item ${x.meal}"><div class="missing-main"><div class="missing-icon">${x.meal==='lunch'?'☀️':'🌙'}</div><div class="missing-copy"><b>${fmtDate(x.date)} · ${x.meal==='lunch'?'午餐':'晚餐'}待补</b><p>${x.pending?'已经提交，正在等你审核':x.rejected?'上次申请被拒绝，可重新提交':'已错过规定打卡时间，系统自动识别'}</p></div></div><button class="btn ${x.pending?'soft':'primary'}" data-auto-makeup="${x.date}|${x.meal}" ${x.pending?'disabled':''}>${x.pending?'待审核':x.rejected?'重新补签':'确认补签'}</button></div>`).join(''):`<div class="empty-state">${state.settings.startDate?'目前没有需要补签的餐次 🎉':'请先绑定初始日期'}</div>`;$('#makeupList').innerHTML=state.makeups.length?state.makeups.slice().reverse().map(x=>reqHtml(x,'makeup')).join(''):'<div class="empty-state">还没有补签申请</div>'}
function reqHtml(x,type){let cls=x.status==='pending'?'pending':x.status==='approved'?'approved':'rejected',tx=x.status==='pending'?'待确认':x.status==='approved'?'已通过':'已拒绝';if(type==='makeup')return `<div class="request-item"><div><b>📝 ${fmtDate(x.date)} · ${x.meal==='lunch'?'午餐':'晚餐'}补签</b><p>${esc(x.reason||'没有填写说明')}<br>${new Date(x.time).toLocaleString('zh-CN')}</p></div><span class="tag ${cls}">${tx}</span></div>`;return `<div class="request-item"><div><b>🧹 ${esc(x.choreName)} · 补 ${x.credit} 天</b><p>${monthLabel(x.month)} · ${esc(x.note||'没有备注')}<br>${new Date(x.time).toLocaleString('zh-CN')}</p></div><span class="tag ${cls}">${tx}</span></div>`}
function renderChores(){$('#choreList').innerHTML=state.chores.length?state.chores.map(x=>`<div class="chore"><div><b>${esc(x.name)}</b><br><small>折抵 ${x.credit} 天</small></div>${isAdmin()?`<button class="btn danger" data-del-chore="${x.id}" style="padding:7px 9px">删除</button>`:''}</div>`).join(''):'<div class="empty-state" style="grid-column:1/-1">还没有家务项目</div>';$('#choreSelect').innerHTML=state.chores.map(x=>`<option value="${x.id}">${esc(x.name)} · ${x.credit} 天</option>`).join('');let prev=new Date();prev.setMonth(prev.getMonth()-1);let max=ym(prev);$('#choreMonth').max=max;if(!$('#choreMonth').value)$('#choreMonth').value=max;let pending=state.choreRequests.filter(x=>x.status==='pending').length;$('#pendingChoreCount').textContent=`${pending} 个待审核家务`;$('#choreRequests').innerHTML=state.choreRequests.length?state.choreRequests.slice().reverse().map(x=>reqHtml(x,'chore')).join(''):'<div class="empty-state">还没有家务补卡记录</div>'}
function renderSettings(){$('#targetDays').value=state.settings.targetDays;$('#rewardEvery').value=state.settings.rewardEvery;$('#demoToggle').classList.toggle('on',!!state.settings.demo);$('#settingsStartDate').textContent=state.settings.startDate?fmtDate(state.settings.startDate):'未绑定';let set=!!state.settings.passwordHash;$('#passwordSetup').style.display=set?'none':'block';$('#passwordSetState').style.display=set?'block':'none'}
function renderAll(){renderToday();renderCalendar();renderRewards();renderMakeups();renderChores();renderSettings()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
let modalLocked=false,startDatePromptOpen=false;
function modal(html,locked=false){modalLocked=locked;$('#modalCard').innerHTML=html;$('#modal').classList.add('show')}
function closeModal(force=false){if(modalLocked&&!force)return;$('#modal').classList.remove('show');modalLocked=false}
async function hash(t){let buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function verifyPassword(message='请输入你设置的管理密码，才能继续。'){if(!state.settings.passwordHash){toast('请先在规则设置里设置管理密码');return false}return await new Promise(resolve=>{modal(`<h3>🔐 管理员确认</h3><p>${esc(message)}</p><input class="input" id="verifyPwd" type="password" placeholder="管理密码" autofocus><div class="modal-actions"><button class="btn soft" id="verifyCancel">取消</button><button class="btn dark" id="verifyBtn">确认</button></div>`);setTimeout(()=>$('#verifyPwd')?.focus(),80);$('#verifyCancel').onclick=()=>{closeModal();resolve(false)};$('#verifyBtn').onclick=async()=>{let ok=(await hash($('#verifyPwd').value))===state.settings.passwordHash;if(ok){closeModal();resolve(true)}else{toast('密码不正确')}}})}
function suggestedStartDate(){let keys=Object.keys(state.checkins).sort();return keys[0]||ymd()}
function ensureStartDate(){if(!cloudReady||state.settings.startDate||startDatePromptOpen)return;if(!isAdmin()){return;}startDatePromptOpen=true;let def=suggestedStartDate();modal(`<h3>📅 第一次使用 · 绑定初始日期</h3><p>从这个日期开始，系统会每天检查午餐和晚餐是否漏打。已经错过时间窗的缺失餐次，会自动进入「补签中心」。</p><div class="field"><label>初始日期</label><input class="input" type="date" id="bindStartDate" max="${ymd()}" value="${def}"></div><div class="note" style="margin-top:10px">绑定后会作为补签识别的起点。建议选择你们正式开始执行打卡规则的那一天。</div><div class="modal-actions"><button class="btn primary" id="confirmStartDate">确认绑定</button></div>`,true);$('#confirmStartDate').onclick=()=>{let v=$('#bindStartDate').value;if(!v||v>ymd()){toast('请选择今天或更早的日期');return}state.settings.startDate=v;startDatePromptOpen=false;closeModal(true);save();toast('初始日期已绑定')}}
async function review(type){let list=(type==='makeup'?state.makeups:state.choreRequests).filter(x=>x.status==='pending');if(!list.length){toast('没有待审核申请');return}if(!(await verifyPassword()))return;let body=list.map(x=>`<div class="request-item" style="margin:8px 0"><div><b>${type==='makeup'?`${fmtDate(x.date)} · ${x.meal==='lunch'?'午餐':'晚餐'}补签`:`${x.choreName} · ${monthLabel(x.month)} · ${x.credit}天`}</b><p>${esc(type==='makeup'?x.reason:x.note)||'无备注'}</p></div><div class="inline"><button class="btn mint-btn" data-review="approve" data-rid="${x.id}" data-type="${type}" style="padding:7px 9px">通过</button><button class="btn danger" data-review="reject" data-rid="${x.id}" data-type="${type}" style="padding:7px 9px">拒绝</button></div></div>`).join('');modal(`<h3>${type==='makeup'?'审核补签':'审核家务补卡'}</h3><p>审核结果会立即写入集章/月度数据。</p>${body}<div class="modal-actions"><button class="btn soft" data-close-modal>完成</button></div>`)}
function applyReview(type,id,action){let arr=type==='makeup'?state.makeups:state.choreRequests,item=arr.find(x=>x.id===id);if(!item)return;item.status=action==='approve'?'approved':'rejected';item.reviewedAt=new Date().toISOString();if(type==='makeup'&&item.status==='approved'){state.checkins[item.date]=state.checkins[item.date]||{};let old=state.checkins[item.date][item.meal];if(!old?.status)state.checkins[item.date][item.meal]={status:'makeup',time:item.reviewedAt,photoId:null,bytes:0}}save();toast(action==='approve'?'已通过并计入数据':'已拒绝');setTimeout(()=>review(type),250)}
function requestAutoMakeup(date,meal){if(mealDone(getDay(date)[meal]))return toast('这餐已经有记录，不需要补签');if(state.makeups.some(x=>x.date===date&&x.meal===meal&&x.status==='pending'))return toast('这餐已经在等待审核');let mealName=meal==='lunch'?'午餐':'晚餐';modal(`<h3>📝 确认补签</h3><p>系统识别到 <b>${fmtDate(date)} · ${mealName}</b> 已经错过打卡时间且没有记录。</p><div class="note">确认后只会提交申请，不会直接补上。仍需要管理员密码审核通过。</div><div class="modal-actions"><button class="btn soft" data-close-modal>取消</button><button class="btn primary" id="confirmAutoMakeup">确认申请</button></div>`);$('#confirmAutoMakeup').onclick=()=>{state.makeups.push({id:uid(),date,meal,reason:'系统自动识别漏打卡',auto:true,status:'pending',time:new Date().toISOString()});closeModal();save();toast('补签申请已提交，等待你确认')}}


function setSyncStatus(text){let el=$('#syncPill');if(el)el.textContent=text}
function applyRoleUI(){
  const admin=isAdmin();
  $('#reviewMakeupBtn').style.display=admin?'':'none'; $('#reviewChoreBtn').style.display=admin?'':'none';
  $('#addReward').style.display=admin?'':'none'; $('#rewardInput').style.display=admin?'':'none';
  $('#addChore').style.display=admin?'':'none'; $('#choreName').style.display=admin?'':'none'; $('#choreCredit').style.display=admin?'':'none';
  const settingsNav=$('#nav button[data-page="settings"]'); if(settingsNav)settingsNav.style.display=admin?'':'none';
  $('#cloudRole').textContent=admin?'管理员':'对象'; $('#cloudSpaceName').textContent=cloud.space?.name||'—'; $('#cloudInvite').textContent=admin?(cloud.space?.invite_code||'—'):'仅管理员可查看';
  renderAll();
}
async function reloadFromCloud(){if(!cloudReady||!navigator.onLine)return;try{let fresh=await cloud.loadState(DEFAULT);state=fresh;localStorage.setItem(cacheKey(),JSON.stringify(state));renderAll();setSyncStatus('已同步 ☁️')}catch(e){console.warn(e);setSyncStatus('离线缓存中')}}
function setupRealtime(){cloud.subscribe(()=>{clearTimeout(remoteReloadTimer);remoteReloadTimer=setTimeout(reloadFromCloud,500)})}
async function enterApp(){
  let cached=load(); if(cached)state=cached;
  try{state=await cloud.loadState(DEFAULT)}catch(e){console.warn('cloud load failed, using cache',e);}
  cloudReady=true; localStorage.setItem(cacheKey(),JSON.stringify(state));
  $('#cloudGate').style.display='none'; $('#mainApp').style.display='block'; setSyncStatus(navigator.onLine?'已连接 ☁️':'离线缓存中');
  applyRoleUI(); setupRealtime(); setTimeout(ensureStartDate,50); syncNow();
}
function gateStep(name){$$('[data-gate-step]').forEach(x=>x.style.display=x.dataset.gateStep===name?'block':'none')}
function gateMsg(msg,bad=false){let el=$('#gateMsg');el.textContent=msg;el.style.color=bad?'#B64655':'#55796C'}
async function bootstrapCloud(){
  $('#mainApp').style.display='none'; $('#cloudGate').style.display='grid';
  if(!cloud.hasConfig()){gateStep('config');return}
  try{let session=await cloud.getSession();if(!session){gateStep('auth');return}let mem=await cloud.loadMembership();if(!mem){gateStep('space');return}await enterApp()}catch(e){console.error(e);let cached=cloud.getCachedSpace();if(cloud.user&&cached){cloud.space=cached;await enterApp();setSyncStatus('离线缓存中');return}gateMsg('连接失败：'+(e.message||'请检查网络与 Supabase 配置'),true);gateStep(cloud.user?'space':'auth')}
}
$('#saveCloudConfig').onclick=()=>{try{cloud.setConfig($('#supabaseUrl').value,$('#supabaseKey').value);gateMsg('配置已保存，可以登录了');gateStep('auth')}catch(e){gateMsg(e.message,true)}};
$('#changeCloudConfig').onclick=()=>gateStep('config');
$('#loginBtn').onclick=async()=>{try{gateMsg('正在登录…');await cloud.signIn($('#authEmail').value,$('#authPassword').value);let mem=await cloud.loadMembership();if(mem)await enterApp();else gateStep('space')}catch(e){gateMsg(e.message||'登录失败',true)}};
$('#signupBtn').onclick=async()=>{try{let d=await cloud.signUp($('#authEmail').value,$('#authPassword').value);if(d.session){let mem=await cloud.loadMembership();if(mem)await enterApp();else gateStep('space')}else gateMsg('注册成功。若项目开启了邮箱确认，请先去邮箱确认后再登录。')}catch(e){gateMsg(e.message||'注册失败',true)}};
$('#createSpaceBtn').onclick=async()=>{try{gateMsg('正在创建情侣空间…');await cloud.createSpace($('#spaceName').value);await enterApp()}catch(e){gateMsg(e.message||'创建失败',true)}};
$('#joinSpaceBtn').onclick=async()=>{try{gateMsg('正在加入…');await cloud.joinSpace($('#inviteCode').value);await enterApp()}catch(e){gateMsg(e.message||'加入失败',true)}};
$('#gateSignOut').onclick=async()=>{await cloud.signOut();gateStep('auth')};
$('#cloudLogout').onclick=async()=>{await cloud.signOut();location.reload()};
$('#cloudResetConfig').onclick=async()=>{await cloud.signOut().catch(()=>{});cloud.clearConfig();location.reload()};
window.addEventListener('online',()=>{setSyncStatus('重新连接中…');syncNow();reloadFromCloud()}); window.addEventListener('offline',()=>setSyncStatus('离线缓存中'));

// navigation
$('#nav').addEventListener('click',e=>{let b=e.target.closest('button[data-page]');if(!b)return;$$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+b.dataset.page).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})});
$('#goMakeupBtn').onclick=()=>$('#nav button[data-page="makeup"]').click();
document.addEventListener('click',async e=>{let up=e.target.closest('[data-upload]');if(up)$('#file-'+up.dataset.upload)?.click();let rm=e.target.closest('[data-remove-photo]');if(rm){let meal=rm.dataset.removePhoto,day=ymd(),v=state.checkins[day]?.[meal];if(v?.photoId)await delPhoto(v.photoId);if(v?.photoPath&&cloudReady)try{await cloud.deletePhoto(v.photoPath)}catch(e){};if(state.checkins[day])delete state.checkins[day][meal];if(cloudReady)try{await cloud.deleteCheckin(day,meal)}catch(e){};save();toast('已移除，可以重新拍啦')}let tr=e.target.closest('[data-toggle-reward]');if(tr&&isAdmin()){let r=state.rewards.find(x=>x.id===tr.dataset.toggleReward);r.enabled=!r.enabled;save()}let dr=e.target.closest('[data-del-reward]');if(dr&&isAdmin()){state.rewards=state.rewards.filter(x=>x.id!==dr.dataset.delReward);if(cloudReady)cloud.deleteReward(dr.dataset.delReward).catch(console.error);save()}let dc=e.target.closest('[data-del-chore]');if(dc&&isAdmin()){state.chores=state.chores.filter(x=>x.id!==dc.dataset.delChore);if(cloudReady)cloud.deleteChore(dc.dataset.delChore).catch(console.error);save()}if(e.target.closest('[data-close-modal]'))closeModal();let rv=e.target.closest('[data-review]');if(rv)applyReview(rv.dataset.type,rv.dataset.rid,rv.dataset.review);let am=e.target.closest('[data-auto-makeup]');if(am&&!am.disabled){let [date,meal]=am.dataset.autoMakeup.split('|');requestAutoMakeup(date,meal)}let cr=e.target.closest('[data-complete-reward]');if(cr)completeReward(cr.dataset.completeReward)});
$('#prevMonth').onclick=()=>{calCursor.setMonth(calCursor.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calCursor.setMonth(calCursor.getMonth()+1);renderCalendar()};$('#thisMonth').onclick=()=>{calCursor=new Date();calCursor.setDate(1);renderCalendar()};
$('#addReward').onclick=()=>{if(!isAdmin())return toast('只有管理员可以修改奖励池');let n=$('#rewardInput').value.trim();if(!n)return toast('先写一个奖励内容');state.rewards.push({id:uid(),name:n,enabled:true});$('#rewardInput').value='';save();toast('奖励已加入奖池')};
$('#rewardMode').onchange=()=>{let f=$('#rewardMode').value==='flip';$('#wheelPanel').style.display=f?'none':'block';$('#flipPanel').style.display=f?'block':'none';if(f)renderFlipCards()};$('#spinBtn').onclick=spin;$('#shuffleCards').onclick=renderFlipCards;
$('#flipCards').addEventListener('click',e=>{let c=e.target.closest('[data-flip]');if(!c||c.classList.contains('open')||!canPlayReward())return;let reward=state.rewards.find(x=>x.id===c.dataset.flip);$$('.flip').forEach(x=>x.classList.add('disabled'));c.classList.remove('disabled');c.classList.add('open');setTimeout(()=>claimReward(reward.name,'flip'),650)});
$('#reviewMakeupBtn').onclick=()=>isAdmin()?review('makeup'):toast('只有管理员可以审核');
$('#addChore').onclick=()=>{if(!isAdmin())return toast('只有管理员可以添加家务');let n=$('#choreName').value.trim(),c=Math.max(1,+$('#choreCredit').value||1);if(!n)return toast('请输入家务名称');state.chores.push({id:uid(),name:n,credit:c});$('#choreName').value='';save();toast('家务已添加')};
$('#submitChore').onclick=()=>{let mon=$('#choreMonth').value,id=$('#choreSelect').value,note=$('#choreNote').value.trim(),ch=state.chores.find(x=>x.id===id);if(!mon||!ch)return toast('请选择月份和家务');if(mon>=ym())return toast('家务补卡用于已经结算的历史月份');state.choreRequests.push({id:uid(),month:mon,choreId:id,choreName:ch.name,credit:ch.credit,note,status:'pending',time:new Date().toISOString()});$('#choreNote').value='';save();toast('家务补卡已提交，等待审核')};$('#reviewChoreBtn').onclick=()=>isAdmin()?review('chore'):toast('只有管理员可以审核');
$('#demoToggle').onclick=async()=>{if(!isAdmin())return toast('只有管理员可以开启测试模式');let wantOn=!state.settings.demo;if(wantOn&&!(await verifyPassword('开启测试模式需要管理员确认。开启后可无限抽奖、翻牌，并解除当天上传时间限制。')))return;state.settings.demo=wantOn;save();toast(wantOn?'测试模式已开启 · 奖励无限测试':'测试模式已关闭')};$('#saveRules').onclick=()=>{if(!isAdmin())return toast('只有管理员可以修改规则');state.settings.targetDays=Math.max(1,+$('#targetDays').value||22);state.settings.rewardEvery=Math.max(1,+$('#rewardEvery').value||15);save();toast('规则已保存')};
$('#savePassword').onclick=async()=>{if(!isAdmin())return toast('只有管理员可以设置管理密码');if(state.settings.passwordHash)return toast('管理密码已经设置，不能直接覆盖');let a=$('#newPassword').value;if(a.length<4)return toast('密码至少 4 位');state.settings.passwordHash=await hash(a);$('#newPassword').value='';save();toast('管理密码已设置并锁定')};
$('#resetPasswordBtn').onclick=()=>{if(!isAdmin())return toast('只有管理员可以重置密码');modal(`<h3>🔑 重置管理密码</h3><p>请输入专用重置口令后，才能重新设置管理密码。</p><input class="input" id="resetCode" type="password" placeholder="重置口令" autofocus><div class="modal-actions"><button class="btn soft" data-close-modal>取消</button><button class="btn dark" id="checkResetCode">继续</button></div>`);setTimeout(()=>$('#resetCode')?.focus(),80);$('#checkResetCode').onclick=()=>{if($('#resetCode').value!=='admin')return toast('重置口令不正确');modal(`<h3>🔐 设置新的管理密码</h3><p>只需要输入一次。保存后会再次锁定，不能直接覆盖。</p><input class="input" id="resetNewPassword" type="password" placeholder="新的管理密码 · 至少 4 位" autofocus><div class="modal-actions"><button class="btn soft" data-close-modal>取消</button><button class="btn dark" id="saveResetPassword">保存新密码</button></div>`);setTimeout(()=>$('#resetNewPassword')?.focus(),80);$('#saveResetPassword').onclick=async()=>{let p=$('#resetNewPassword').value;if(p.length<4)return toast('密码至少 4 位');state.settings.passwordHash=await hash(p);closeModal();save();toast('管理密码已重置并重新锁定')}}};
$('#exportData').onclick=()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`准时吃饭打卡备份_${ymd()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let x=JSON.parse(await f.text());state=Object.assign(clone(DEFAULT),x,{settings:Object.assign({},DEFAULT.settings,x.settings||{})});save();toast('数据已导入（照片需保留原浏览器数据）')}catch(err){toast('JSON 文件无法读取')}};
$('#resetData').onclick=()=>modal(`<h3>真的要清空吗？</h3><p>这会删除所有打卡、奖励、补签、家务和设置。照片数据库也会一起清空。</p><div class="modal-actions"><button class="btn soft" data-close-modal>取消</button><button class="btn danger" id="confirmReset">全部清空</button></div>`);
document.addEventListener('click',async e=>{if(e.target.id==='confirmReset'){if(!isAdmin())return toast('只有管理员可以清空数据');try{if(cloudReady)await cloud.resetSpaceData();state=clone(DEFAULT);if(db){let tx=db.transaction('photos','readwrite');tx.objectStore('photos').clear()}closeModal();save();toast('已清空云端与本地数据')}catch(err){console.error(err);toast('清空失败：'+(err.message||'未知错误'))}}});
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
setInterval(()=>{renderToday()},60000);
initDB().catch(()=>renderAll());renderAll();bootstrapCloud();
})();